### ISSUE TITLE
ngsiproxy not running

### ISSUE THREAD

**Issue by sdhouib** [conwetlab/ngsi-proxy#5]
I have just installed the latest ngsiproxy using this command:
 docker run --name beincpps-ngsiproxy -d fiware/ngsiproxy
The docker container is running properly: docker container ps -a
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                    PORTS                    NAMES
9c5ade363d3f        fiware/ngsiproxy          "/bin/sh -c ngsi-p..."   11 minutes ago      Up 11 minutes             3000/tcp                 beincpps-ngsiproxy

But when trying to access in firefox the address http://localhost:3000 , the ngsiproxy is not responding and the page is not accessible.

Do you have any idea?

Thanks!

**Comment by aarranz** [comment]
Sorry, docker hub documentation was not finished.

Although the image includes an `EXPORT 3000` command, you will need to publish that port on the host if you want to be able to access the service in the way you are indicating. So, if you execute:

```
docker run --name beincpps-ngsiproxy -d -p 3000:3000 fiware/ngsiproxy
```

You should be able to access http://localhost:3000 (taking into account that `ngsi-proxy` does not provide a user interface yet)

**Comment by sdhouib** [comment]
Thanks!

**Comment by Saya9** [comment]
Does ngsi proxy require any additional configuration to push notifications from context broker to wirecloud widget/operator?
