### ISSUE TITLE
Configuration for NGSI proxy

### ISSUE THREAD

**Issue by Saya9** [conwetlab/ngsi-proxy#8]
I have installed the latest ngsiproxy on docker container.I am not able to receive notifications from context broker in wirecloud widget though subscription is created successfully.
Is there a need of additional configuration than issuing
docker run --name some-ngsiproxy -p 3000:3000 -d fiware/ngsiproxy ?

**Comment by aarranz** [comment]
The ngsi proxy should not require any extra configuration step.

Are you using any of the available WireCloud widgets/operators? In that case, which and using what configuration?

Or, are you developing a custom widget/operator? In that case, can you provide the fragment in which you are creating the subscription?

**Comment by Saya9** [comment]
I am using ngsi source operator from https://github.com/wirecloud-fiware/ngsi-source-operator .But the widget that consumes data from this operator is customized. The problem I am facing is that when callbacks are made only subscription id is created but updated entity is not reaching the ngsi source operator (onNotify).

**Comment by Saya9** [comment]
Seems like there is an  issue in docker container communication .Thanks for the help

**Comment by aarranz** [comment]
You are welcome!
